apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argoapplication
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bertiniawara/jenkins-k8s1.git
    targetRevision: HEAD
    path: deploy/
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
