apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven-demo
  template:
    metadata:
      labels:
        app: maven-demo
    spec:
      containers:
      - name: maven-demo
        image: betiniawara842/maven-demo
        ports:
        - containerPort: 8080
